upstream mtdd_grpc_backend {
    server unix:/run/mtdd/grpc.sock;
    keepalive 16;
}

server {
    listen 50051 http2;

    location / {
        grpc_pass grpc://mtdd_grpc_backend;
        grpc_read_timeout 3600s;
        grpc_send_timeout 3600s;
        client_max_body_size 0;
    }
}
